### ISSUE TITLE
awx won't start. 

### ISSUE THREAD

**Issue by bayeslearner** [fidanf/my-devops-box#5]
It seems to be a permission issue with the default setting.  

awx_web log:
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied

postgres logs: 
2020-11-01 02:12:19.489 UTC [29] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Permission denied

**Comment by bayeslearner** [comment]
I commented out 
#chown -R vagrant:vagrant /home/vagrant
Do I need this? 

and then I ran into this issue: 
https://github.com/ansible/awx/issues/6792

after I ran 
docker exec awx_task awx-manage migrate

The deadlock seems to be resolved.

**Comment by chriskacerguis** [comment]
Just wanted to add that as of 15.0.1 this is still a problem, fixed by (same as above, but added the -it to see the progress):

```
docker exec -it awx_task awx-manage migrate
```

**Comment by fidanf** [comment]
I have bumped the AWX default version to 16.0.0, and it worked with no problem, having the `awx_inventory` file untouched.
Please pull master, try again from scratch and let me know if you encounter any problems.
